steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t us-east1-docker.pkg.dev/poetic-brace-430620-b4/store-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east1-docker.pkg.dev/poetic-brace-430620-b4/store-registry/orders-ms',
      ]

availableSecrets:
  secretManager:
    - versionName: projects/891522991085/secrets/ORDERS_DATABASE_URL/versions/1
      env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY
